// g++ -std=c++17 main.cpp -o main && ./main
#include <iostream>
#include <string_view>

template <typename T>
constexpr auto type_name() {
    std::string_view
        name = __PRETTY_FUNCTION__,
        prefix = "constexpr auto type_name() [with T = ",
        suffix = "]";

    name.remove_prefix(prefix.size());
    name.remove_suffix(suffix.size());

    return name;
}

template <typename TA, typename TB>
void print_types(){
    TA a = 0;
    TB b = 0;

    auto ab = a + b;

    std::cout
        << type_name<decltype(a)>() << " + "
        << type_name<decltype(b)>() << " = "
        << type_name<decltype(ab)>() << std::endl;
}

int main(){
    print_types<char, char>();
    print_types<char, short>();
    print_types<char, int>();
    print_types<char, long>();
    print_types<char, long long>();
    print_types<char, float>();
    print_types<char, double>();
    print_types<char, long double>();
    print_types<char, signed char>();
    print_types<char, unsigned char>();
    print_types<char, signed short>();
    print_types<char, unsigned short>();
    print_types<char, signed int>();
    print_types<char, unsigned int>();
    print_types<char, signed long>();
    print_types<char, unsigned long>();
    print_types<char, signed long long>();
    print_types<char, unsigned long long>();
    print_types<short, char>();
    print_types<short, short>();
    print_types<short, int>();
    print_types<short, long>();
    print_types<short, long long>();
    print_types<short, float>();
    print_types<short, double>();
    print_types<short, long double>();
    print_types<short, signed char>();
    print_types<short, unsigned char>();
    print_types<short, signed short>();
    print_types<short, unsigned short>();
    print_types<short, signed int>();
    print_types<short, unsigned int>();
    print_types<short, signed long>();
    print_types<short, unsigned long>();
    print_types<short, signed long long>();
    print_types<short, unsigned long long>();
    print_types<int, char>();
    print_types<int, short>();
    print_types<int, int>();
    print_types<int, long>();
    print_types<int, long long>();
    print_types<int, float>();
    print_types<int, double>();
    print_types<int, long double>();
    print_types<int, signed char>();
    print_types<int, unsigned char>();
    print_types<int, signed short>();
    print_types<int, unsigned short>();
    print_types<int, signed int>();
    print_types<int, unsigned int>();
    print_types<int, signed long>();
    print_types<int, unsigned long>();
    print_types<int, signed long long>();
    print_types<int, unsigned long long>();
    print_types<long, char>();
    print_types<long, short>();
    print_types<long, int>();
    print_types<long, long>();
    print_types<long, long long>();
    print_types<long, float>();
    print_types<long, double>();
    print_types<long, long double>();
    print_types<long, signed char>();
    print_types<long, unsigned char>();
    print_types<long, signed short>();
    print_types<long, unsigned short>();
    print_types<long, signed int>();
    print_types<long, unsigned int>();
    print_types<long, signed long>();
    print_types<long, unsigned long>();
    print_types<long, signed long long>();
    print_types<long, unsigned long long>();
    print_types<long long, char>();
    print_types<long long, short>();
    print_types<long long, int>();
    print_types<long long, long>();
    print_types<long long, long long>();
    print_types<long long, float>();
    print_types<long long, double>();
    print_types<long long, long double>();
    print_types<long long, signed char>();
    print_types<long long, unsigned char>();
    print_types<long long, signed short>();
    print_types<long long, unsigned short>();
    print_types<long long, signed int>();
    print_types<long long, unsigned int>();
    print_types<long long, signed long>();
    print_types<long long, unsigned long>();
    print_types<long long, signed long long>();
    print_types<long long, unsigned long long>();
    print_types<float, char>();
    print_types<float, short>();
    print_types<float, int>();
    print_types<float, long>();
    print_types<float, long long>();
    print_types<float, float>();
    print_types<float, double>();
    print_types<float, long double>();
    print_types<float, signed char>();
    print_types<float, unsigned char>();
    print_types<float, signed short>();
    print_types<float, unsigned short>();
    print_types<float, signed int>();
    print_types<float, unsigned int>();
    print_types<float, signed long>();
    print_types<float, unsigned long>();
    print_types<float, signed long long>();
    print_types<float, unsigned long long>();
    print_types<double, char>();
    print_types<double, short>();
    print_types<double, int>();
    print_types<double, long>();
    print_types<double, long long>();
    print_types<double, float>();
    print_types<double, double>();
    print_types<double, long double>();
    print_types<double, signed char>();
    print_types<double, unsigned char>();
    print_types<double, signed short>();
    print_types<double, unsigned short>();
    print_types<double, signed int>();
    print_types<double, unsigned int>();
    print_types<double, signed long>();
    print_types<double, unsigned long>();
    print_types<double, signed long long>();
    print_types<double, unsigned long long>();
    print_types<long double, char>();
    print_types<long double, short>();
    print_types<long double, int>();
    print_types<long double, long>();
    print_types<long double, long long>();
    print_types<long double, float>();
    print_types<long double, double>();
    print_types<long double, long double>();
    print_types<long double, signed char>();
    print_types<long double, unsigned char>();
    print_types<long double, signed short>();
    print_types<long double, unsigned short>();
    print_types<long double, signed int>();
    print_types<long double, unsigned int>();
    print_types<long double, signed long>();
    print_types<long double, unsigned long>();
    print_types<long double, signed long long>();
    print_types<long double, unsigned long long>();
    print_types<signed char, char>();
    print_types<signed char, short>();
    print_types<signed char, int>();
    print_types<signed char, long>();
    print_types<signed char, long long>();
    print_types<signed char, float>();
    print_types<signed char, double>();
    print_types<signed char, long double>();
    print_types<signed char, signed char>();
    print_types<signed char, unsigned char>();
    print_types<signed char, signed short>();
    print_types<signed char, unsigned short>();
    print_types<signed char, signed int>();
    print_types<signed char, unsigned int>();
    print_types<signed char, signed long>();
    print_types<signed char, unsigned long>();
    print_types<signed char, signed long long>();
    print_types<signed char, unsigned long long>();
    print_types<unsigned char, char>();
    print_types<unsigned char, short>();
    print_types<unsigned char, int>();
    print_types<unsigned char, long>();
    print_types<unsigned char, long long>();
    print_types<unsigned char, float>();
    print_types<unsigned char, double>();
    print_types<unsigned char, long double>();
    print_types<unsigned char, signed char>();
    print_types<unsigned char, unsigned char>();
    print_types<unsigned char, signed short>();
    print_types<unsigned char, unsigned short>();
    print_types<unsigned char, signed int>();
    print_types<unsigned char, unsigned int>();
    print_types<unsigned char, signed long>();
    print_types<unsigned char, unsigned long>();
    print_types<unsigned char, signed long long>();
    print_types<unsigned char, unsigned long long>();
    print_types<signed short, char>();
    print_types<signed short, short>();
    print_types<signed short, int>();
    print_types<signed short, long>();
    print_types<signed short, long long>();
    print_types<signed short, float>();
    print_types<signed short, double>();
    print_types<signed short, long double>();
    print_types<signed short, signed char>();
    print_types<signed short, unsigned char>();
    print_types<signed short, signed short>();
    print_types<signed short, unsigned short>();
    print_types<signed short, signed int>();
    print_types<signed short, unsigned int>();
    print_types<signed short, signed long>();
    print_types<signed short, unsigned long>();
    print_types<signed short, signed long long>();
    print_types<signed short, unsigned long long>();
    print_types<unsigned short, char>();
    print_types<unsigned short, short>();
    print_types<unsigned short, int>();
    print_types<unsigned short, long>();
    print_types<unsigned short, long long>();
    print_types<unsigned short, float>();
    print_types<unsigned short, double>();
    print_types<unsigned short, long double>();
    print_types<unsigned short, signed char>();
    print_types<unsigned short, unsigned char>();
    print_types<unsigned short, signed short>();
    print_types<unsigned short, unsigned short>();
    print_types<unsigned short, signed int>();
    print_types<unsigned short, unsigned int>();
    print_types<unsigned short, signed long>();
    print_types<unsigned short, unsigned long>();
    print_types<unsigned short, signed long long>();
    print_types<unsigned short, unsigned long long>();
    print_types<signed int, char>();
    print_types<signed int, short>();
    print_types<signed int, int>();
    print_types<signed int, long>();
    print_types<signed int, long long>();
    print_types<signed int, float>();
    print_types<signed int, double>();
    print_types<signed int, long double>();
    print_types<signed int, signed char>();
    print_types<signed int, unsigned char>();
    print_types<signed int, signed short>();
    print_types<signed int, unsigned short>();
    print_types<signed int, signed int>();
    print_types<signed int, unsigned int>();
    print_types<signed int, signed long>();
    print_types<signed int, unsigned long>();
    print_types<signed int, signed long long>();
    print_types<signed int, unsigned long long>();
    print_types<unsigned int, char>();
    print_types<unsigned int, short>();
    print_types<unsigned int, int>();
    print_types<unsigned int, long>();
    print_types<unsigned int, long long>();
    print_types<unsigned int, float>();
    print_types<unsigned int, double>();
    print_types<unsigned int, long double>();
    print_types<unsigned int, signed char>();
    print_types<unsigned int, unsigned char>();
    print_types<unsigned int, signed short>();
    print_types<unsigned int, unsigned short>();
    print_types<unsigned int, signed int>();
    print_types<unsigned int, unsigned int>();
    print_types<unsigned int, signed long>();
    print_types<unsigned int, unsigned long>();
    print_types<unsigned int, signed long long>();
    print_types<unsigned int, unsigned long long>();
    print_types<signed long, char>();
    print_types<signed long, short>();
    print_types<signed long, int>();
    print_types<signed long, long>();
    print_types<signed long, long long>();
    print_types<signed long, float>();
    print_types<signed long, double>();
    print_types<signed long, long double>();
    print_types<signed long, signed char>();
    print_types<signed long, unsigned char>();
    print_types<signed long, signed short>();
    print_types<signed long, unsigned short>();
    print_types<signed long, signed int>();
    print_types<signed long, unsigned int>();
    print_types<signed long, signed long>();
    print_types<signed long, unsigned long>();
    print_types<signed long, signed long long>();
    print_types<signed long, unsigned long long>();
    print_types<unsigned long, char>();
    print_types<unsigned long, short>();
    print_types<unsigned long, int>();
    print_types<unsigned long, long>();
    print_types<unsigned long, long long>();
    print_types<unsigned long, float>();
    print_types<unsigned long, double>();
    print_types<unsigned long, long double>();
    print_types<unsigned long, signed char>();
    print_types<unsigned long, unsigned char>();
    print_types<unsigned long, signed short>();
    print_types<unsigned long, unsigned short>();
    print_types<unsigned long, signed int>();
    print_types<unsigned long, unsigned int>();
    print_types<unsigned long, signed long>();
    print_types<unsigned long, unsigned long>();
    print_types<unsigned long, signed long long>();
    print_types<unsigned long, unsigned long long>();
    print_types<signed long long, char>();
    print_types<signed long long, short>();
    print_types<signed long long, int>();
    print_types<signed long long, long>();
    print_types<signed long long, long long>();
    print_types<signed long long, float>();
    print_types<signed long long, double>();
    print_types<signed long long, long double>();
    print_types<signed long long, signed char>();
    print_types<signed long long, unsigned char>();
    print_types<signed long long, signed short>();
    print_types<signed long long, unsigned short>();
    print_types<signed long long, signed int>();
    print_types<signed long long, unsigned int>();
    print_types<signed long long, signed long>();
    print_types<signed long long, unsigned long>();
    print_types<signed long long, signed long long>();
    print_types<signed long long, unsigned long long>();
    print_types<unsigned long long, char>();
    print_types<unsigned long long, short>();
    print_types<unsigned long long, int>();
    print_types<unsigned long long, long>();
    print_types<unsigned long long, long long>();
    print_types<unsigned long long, float>();
    print_types<unsigned long long, double>();
    print_types<unsigned long long, long double>();
    print_types<unsigned long long, signed char>();
    print_types<unsigned long long, unsigned char>();
    print_types<unsigned long long, signed short>();
    print_types<unsigned long long, unsigned short>();
    print_types<unsigned long long, signed int>();
    print_types<unsigned long long, unsigned int>();
    print_types<unsigned long long, signed long>();
    print_types<unsigned long long, unsigned long>();
    print_types<unsigned long long, signed long long>();
    print_types<unsigned long long, unsigned long long>();
}
